import { Product, Currency } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    sku: 'HW-LAP-001',
    name: 'ProBook Laptop 15"',
    retailPrice: 1299.99,
    costPrice: 850.00,
    stock: 25,
    lowStockThreshold: 10,
    priceHistory: [],
    categoryIds: ['cat_electronics', 'cat_computers'],
    variationTypes: [],
    variants: [],
  },
  {
    id: 'prod_2',
    sku: 'HW-MON-002',
    name: 'UltraWide Monitor 29"',
    retailPrice: 499.99,
    costPrice: 320.50,
    stock: 40,
    lowStockThreshold: 15,
    priceHistory: [],
    categoryIds: ['cat_electronics', 'cat_accessories'],
    variationTypes: [],
    variants: [],
  },
  {
    id: 'prod_3',
    sku: 'AC-KBD-003',
    name: 'Mechanical Keyboard',
    retailPrice: 149.99,
    costPrice: 95.00,
    stock: 75,
    lowStockThreshold: 20,
    priceHistory: [],
    categoryIds: ['cat_electronics', 'cat_accessories'],
    variationTypes: [],
    variants: [],
  },
  {
    id: 'prod_4',
    sku: 'AC-MSE-004',
    name: 'Wireless Ergonomic Mouse',
    retailPrice: 79.99,
    costPrice: 45.00,
    stock: 120,
    lowStockThreshold: 30,
    priceHistory: [],
    categoryIds: ['cat_electronics', 'cat_accessories'],
    variationTypes: [],
    variants: [],
  },
  {
    id: 'prod_5',
    sku: 'HW-CAM-005',
    name: '4K Webcam Pro',
    retailPrice: 199.99,
    costPrice: 130.00,
    stock: 8,
    lowStockThreshold: 10,
    priceHistory: [],
    categoryIds: ['cat_electronics', 'cat_accessories'],
    variationTypes: [],
    variants: [],
  },
  {
    id: 'prod_6',
    sku: 'AC-HDP-006',
    name: 'Noise-Cancelling Headphones',
    retailPrice: 249.99,
    costPrice: 180.00,
    stock: 50,
    lowStockThreshold: 15,
    priceHistory: [],
    categoryIds: ['cat_electronics', 'cat_accessories'],
    variationTypes: [],
    variants: [],
  },
  {
    id: 'prod_7',
    sku: 'AP-TSH-007',
    name: 'Classic Crew T-Shirt',
    retailPrice: 24.99,
    costPrice: 10.00,
    stock: 127,
    lowStockThreshold: 10,
    priceHistory: [],
    categoryIds: ['cat_apparel'],
    variationTypes: [
      {
        id: 'vt_color_1',
        name: 'Color',
        options: [ { id: 'opt_c_1', name: 'White' }, { id: 'opt_c_2', name: 'Black' } ],
      },
      {
        id: 'vt_size_1',
        name: 'Size',
        options: [ { id: 'opt_s_1', name: 'S' }, { id: 'opt_s_2', name: 'M' }, { id: 'opt_s_3', name: 'L' } ],
      },
    ],
    variants: [
      { id: 'var_1', options: { Color: 'White', Size: 'S' }, skuSuffix: 'WH-S', retailPrice: 24.99, costPrice: 10.00, stock: 20 },
      { id: 'var_2', options: { Color: 'White', Size: 'M' }, skuSuffix: 'WH-M', retailPrice: 24.99, costPrice: 10.00, stock: 30 },
      { id: 'var_3', options: { Color: 'White', Size: 'L' }, skuSuffix: 'WH-L', retailPrice: 24.99, costPrice: 10.00, stock: 15 },
      { id: 'var_4', options: { Color: 'Black', Size: 'S' }, skuSuffix: 'BK-S', retailPrice: 24.99, costPrice: 10.00, stock: 22 },
      { id: 'var_5', options: { Color: 'Black', Size: 'M' }, skuSuffix: 'BK-M', retailPrice: 24.99, costPrice: 10.00, stock: 28 },
      { id: 'var_6', options: { Color: 'Black', Size: 'L' }, skuSuffix: 'BK-L', retailPrice: 24.99, costPrice: 10.00, stock: 12 },
    ],
  },
];

export const DEFAULT_CURRENCIES: Currency[] = [
    { code: 'USD', name: 'United States Dollar', symbol: '$' },
    { code: 'EUR', name: 'Euro', symbol: '€' },
    { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
    { code: 'GBP', name: 'British Pound Sterling', symbol: '£' },
    { code: 'AUD', name: 'Australian Dollar', symbol: 'A$' },
    { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$' },
    { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr' },
    { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
    { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
    { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨' },
];

export const TIMEZONE_OPTIONS = [
  { value: 'Etc/GMT+11', label: 'UTC-11:00' },
  { value: 'Etc/GMT+10', label: 'UTC-10:00' },
  { value: 'Pacific/Marquesas', label: 'UTC-09:30' },
  { value: 'Etc/GMT+9', label: 'UTC-09:00' },
  { value: 'Etc/GMT+8', label: 'UTC-08:00' },
  { value: 'Etc/GMT+7', label: 'UTC-07:00' },
  { value: 'Etc/GMT+6', label: 'UTC-06:00' },
  { value: 'Etc/GMT+5', label: 'UTC-05:00' },
  { value: 'America/Caracas', label: 'UTC-04:30' },
  { value: 'Etc/GMT+4', label: 'UTC-04:00' },
  { value: 'America/St_Johns', label: 'UTC-03:30' },
  { value: 'Etc/GMT+3', label: 'UTC-03:00' },
  { value: 'Etc/GMT+2', label: 'UTC-02:00' },
  { value: 'Etc/GMT+1', label: 'UTC-01:00' },
  { value: 'Etc/GMT+0', label: 'UTC+00:00' },
  { value: 'Etc/GMT-1', label: 'UTC+01:00' },
  { value: 'Etc/GMT-2', label: 'UTC+02:00' },
  { value: 'Etc/GMT-3', label: 'UTC+03:00' },
  { value: 'Asia/Tehran', label: 'UTC+03:30' },
  { value: 'Etc/GMT-4', label: 'UTC+04:00' },
  { value: 'Asia/Kabul', label: 'UTC+04:30' },
  { value: 'Etc/GMT-5', label: 'UTC+05:00' },
  { value: 'Asia/Kolkata', label: 'UTC+05:30' },
  { value: 'Asia/Kathmandu', label: 'UTC+05:45' },
  { value: 'Etc/GMT-6', label: 'UTC+06:00' },
  { value: 'Asia/Yangon', label: 'UTC+06:30' },
  { value: 'Etc/GMT-7', label: 'UTC+07:00' },
  { value: 'Etc/GMT-8', label: 'UTC+08:00' },
  { value: 'Australia/Eucla', label: 'UTC+08:45' },
  { value: 'Etc/GMT-9', label: 'UTC+09:00' },
  { value: 'Australia/Darwin', label: 'UTC+09:30' },
  { value: 'Etc/GMT-10', label: 'UTC+10:00' },
  { value: 'Australia/Lord_Howe', label: 'UTC+10:30' },
  { value: 'Etc/GMT-11', label: 'UTC+11:00' },
  { value: 'Etc/GMT-12', label: 'UTC+12:00' },
  { value: 'Pacific/Chatham', label: 'UTC+12:45' },
  { value: 'Etc/GMT-13', label: 'UTC+13:00' },
];