
import { Product, Currency, Customer, Supplier } from './types';

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    sku: 'HW-LAP-001',
    name: 'ProBook Laptop 15"',
    retailPrice: 1299.99,
    costPrice: 850.00,
    stock: 25,
    lowStockThreshold: 10,
    priceHistory: [],
    categoryIds: ['cat_electronics', 'cat_computers'],
    variationTypes: [],
    variants: [],
  },
  {
    id: 'prod_2',
    sku: 'HW-MON-002',
    name: 'UltraWide Monitor 29"',
    retailPrice: 499.99,
    costPrice: 320.50,
    stock: 40,
    lowStockThreshold: 15,
    priceHistory: [],
    categoryIds: ['cat_electronics', 'cat_accessories'],
    variationTypes: [],
    variants: [],
  },
  {
    id: 'prod_3',
    sku: 'AC-KBD-003',
    name: 'Mechanical Keyboard',
    retailPrice: 149.99,
    costPrice: 95.00,
    stock: 75,
    lowStockThreshold: 20,
    priceHistory: [],
    categoryIds: ['cat_electronics', 'cat_accessories'],
    variationTypes: [],
    variants: [],
  },
  {
    id: 'prod_4',
    sku: 'AC-MSE-004',
    name: 'Wireless Ergonomic Mouse',
    retailPrice: 79.99,
    costPrice: 45.00,
    stock: 120,
    lowStockThreshold: 30,
    priceHistory: [],
    categoryIds: ['cat_electronics', 'cat_accessories'],
    variationTypes: [],
    variants: [],
  },
  {
    id: 'prod_5',
    sku: 'HW-CAM-005',
    name: '4K Webcam Pro',
    retailPrice: 199.99,
    costPrice: 130.00,
    stock: 8,
    lowStockThreshold: 10,
    priceHistory: [],
    categoryIds: ['cat_electronics', 'cat_accessories'],
    variationTypes: [],
    variants: [],
  },
  {
    id: 'prod_6',
    sku: 'AC-HDP-006',
    name: 'Noise-Cancelling Headphones',
    retailPrice: 249.99,
    costPrice: 180.00,
    stock: 50,
    lowStockThreshold: 15,
    priceHistory: [],
    categoryIds: ['cat_electronics', 'cat_accessories'],
    variationTypes: [],
    variants: [],
  },
  {
    id: 'prod_7',
    sku: 'AP-TSH-007',
    name: 'Classic Crew T-Shirt',
    retailPrice: 24.99,
    costPrice: 10.00,
    stock: 127,
    lowStockThreshold: 10,
    priceHistory: [],
    categoryIds: ['cat_apparel'],
    variationTypes: [
      {
        id: 'vt_color_1',
        name: 'Color',
        options: [ { id: 'opt_c_1', name: 'White' }, { id: 'opt_c_2', name: 'Black' } ],
      },
      {
        id: 'vt_size_1',
        name: 'Size',
        options: [ { id: 'opt_s_1', name: 'S' }, { id: 'opt_s_2', name: 'M' }, { id: 'opt_s_3', name: 'L' } ],
      },
    ],
    variants: [
      { id: 'var_1', options: { Color: 'White', Size: 'S' }, skuSuffix: 'WH-S', retailPrice: 24.99, costPrice: 10.00, stock: 20 },
      { id: 'var_2', options: { Color: 'White', Size: 'M' }, skuSuffix: 'WH-M', retailPrice: 24.99, costPrice: 10.00, stock: 30 },
      { id: 'var_3', options: { Color: 'White', Size: 'L' }, skuSuffix: 'WH-L', retailPrice: 24.99, costPrice: 10.00, stock: 15 },
      { id: 'var_4', options: { Color: 'Black', Size: 'S' }, skuSuffix: 'BK-S', retailPrice: 24.99, costPrice: 10.00, stock: 22 },
      { id: 'var_5', options: { Color: 'Black', Size: 'M' }, skuSuffix: 'BK-M', retailPrice: 24.99, costPrice: 10.00, stock: 28 },
      { id: 'var_6', options: { Color: 'Black', Size: 'L' }, skuSuffix: 'BK-L', retailPrice: 24.99, costPrice: 10.00, stock: 12 },
    ],
  },
];

export const DEFAULT_CURRENCIES: Currency[] = [
    { code: 'USD', name: 'United States Dollar', symbol: '$' },
    { code: 'EUR', name: 'Euro', symbol: '€' },
    { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
    { code: 'GBP', name: 'British Pound Sterling', symbol: '£' },
    { code: 'AUD', name: 'Australian Dollar', symbol: 'A$' },
    { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$' },
    { code: 'CHF', name: 'Swiss Franc', symbol: 'Fr' },
    { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
    { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
    { code: 'PKR', name: 'Pakistani Rupee', symbol: '₨' },
];

export const INITIAL_CUSTOMERS: Customer[] = [
    { id: 'cust_1', publicId: 'CUS-9X2K1M', name: 'John Doe', email: 'john@example.com', phone: '555-0101', address: '123 Main St', dateAdded: new Date().toISOString() },
    { id: 'cust_2', publicId: 'CUS-B4L8P2', name: 'Jane Smith', email: 'jane@example.com', phone: '555-0102', address: '456 Oak Ave', dateAdded: new Date().toISOString() },
    { id: 'cust_3', publicId: 'CUS-H7N3R9', name: 'Bob Johnson', email: 'bob@example.com', phone: '555-0103', address: '789 Pine Ln', dateAdded: new Date().toISOString() },
];

export const INITIAL_SUPPLIERS: Supplier[] = [
    { id: 'sup_1', publicId: 'SUP-K2M5T8', name: 'Global Tech Distributors', contactPerson: 'Alice Walker', email: 'alice@globaltech.com', phone: '555-1111', address: '101 Tech Blvd' },
    { id: 'sup_2', publicId: 'SUP-R9Q4W1', name: 'Office Essentials Co.', contactPerson: 'Mark Davis', email: 'mark@officeessentials.com', phone: '555-2222', address: '202 Paper St' },
    { id: 'sup_3', publicId: 'SUP-X6Z3J7', name: 'Premium Apparel Wholesalers', contactPerson: 'Sarah Lee', email: 'sarah@premiumapparel.com', phone: '555-3333', address: '303 Fabric Rd' },
];
